# Generated by Django 3.2.9 on 2022-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_dog',
            name='file',
        ),
        migrations.AddField(
            model_name='cat_dog',
            name='cat_dog_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cat_dog',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
